// <auto-generated />
using GSNet24.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GSNet24.Migrations
{
    [DbContext(typeof(AppContextDb))]
    [Migration("20241121024907_AddAparelho")]
    partial class AddAparelho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GSNet24.Model.AparelhoModel", b =>
                {
                    b.Property<int>("AparelhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_APARELHO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AparelhoId"));

                    b.Property<string>("NomeAparelho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_APARELHO");

                    b.Property<int>("TempoUso")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TEMPO_UTILIZADO");

                    b.HasKey("AparelhoId");

                    b.ToTable("APARELHO_NET");
                });
#pragma warning restore 612, 618
        }
    }
}
